# COWORKMILL の Q&A データ（形式は QUESTIONS_FORMAT.py と同じ。build_site.py が読む）
# 事実は cowork_facilities.py の各施設の記事データ（facts・concept・steps の本文）にあることだけ。推測しない。数字は記事のまま。
# 写真番号はその施設の IMG30 のキー（hero か steps で使っている番号だけ）。
# 書き方: 敬体。一文短く。ひらがな開きしない。読む人に指図しない。棘のある言葉を使わない。
QUESTIONS = [
 dict(slug='difference', q='コワーキングスペースとシェアオフィス、何が違うの？',
      a='コワーキングは共用の席を分け合う使い方、シェアオフィスは鍵のかかる部屋を借りる使い方です。実際には一つの施設に両方が入っていることが多く、co-ba ebisu は1階がコワーキング、2階が個室オフィスです。',
      desc='コワーキングとシェアオフィスの違いを、co-ba ebisu・LIFORK 大手町・co-lab 渋谷キャスト・ARCH の公式情報から。',
      secs=[
       ('co-ba-ebisu', '1階が共用の席、2階が鍵のかかる部屋',
        ['co-ba ebisu は、1階がコワーキング、2階が個室オフィスです。1階は毎日24時間使えるフリーアドレスが月30,000円、固定席は BOOTH が月65,000円です。', '2階は約31〜72㎡の部屋を2年の定期契約で借ります。同じ建物の中に、席を借りる入口と部屋を借りる入口が並んでいます。'],
        [('co-ba-ebisu', 1), ('co-ba-ebisu', 6)]),
       ('lifork-otemachi', '4名から30名までの部屋を、13タイプ',
        ['LIFORK 大手町のシェアオフィスは、4名用から20〜30名用まで13タイプの部屋です。24時間365日使え、光熱費は賃料に含まれます。', '一つの会社が一つの部屋を借りる形で、入会金は賃料1か月分、保証金は賃料1.1か月分です。席ではなく部屋の単位で契約する、シェアオフィスの分かりやすい例です。'],
        [('lifork-otemachi', 2)]),
       ('co-lab-shibuya-cast', '1〜2人のブースから22人のルームまで',
        ['co-lab 渋谷キャストは、クリエイターのためのシェアオフィスです。1〜2人のブース16、3〜5人のスタジオ7、4〜12人のアトリエ8、12〜22人のルーム4がそろいます。', '席を固定しないフレックスは月15,000円から、1人用のデスクは月42,000円からです。部屋の大きさを細かく分けているので、一人でも小さなチームでも選べます。'],
        [('co-lab-shibuya-cast', 2), ('co-lab-shibuya-cast', 3)]),
       ('toranomon-hills-arch', 'CO-WORK と SMALL OFFICE を同じフロアに',
        ['ARCH の CO-WORK は「利用シーンに応じて、働く場所を選べる多彩なワークスペース」です。電源と通信は全席に備わります。', 'SMALL OFFICE はセキュリティの確保されたセカンドオフィスです。同じ3,800㎡のフロアに、開いた席と閉じた部屋の両方があります。'],
        [('toranomon-hills-arch', 2), ('toranomon-hills-arch', 4)]),
      ],
      ctx=dict(term='シェアオフィス', yomi='シェアオフィス', title='シェアオフィスとは', body=['一つの建物の中を部屋に分けて、複数の会社や個人が借りる形のオフィスです。受付やラウンジ、会議室を共用にします。', 'コワーキングとの線引きは施設によって違います。共用の席が中心ならコワーキング、鍵のかかる部屋が中心ならシェアオフィスと呼ばれることが多いです。']),
      items=['co-ba-ebisu', 'lifork-otemachi', 'co-lab-shibuya-cast', 'toranomon-hills-arch']),

 dict(slug='drop-in', q='会員でなくても使える場所はあるの？',
      a='あります。1日単位のドロップイン、30分単位の部屋貸し、見学ツアーなど、入口の形はさまざまです。co-ba ebisu のドロップインは平日10時〜19時で1日2,000円です。',
      desc='会員でなくても使えるコワーキングの入口を、co-ba ebisu・MIDORI.so・LIFORK 大手町・100BANCH の公式情報から。',
      secs=[
       ('co-ba-ebisu', '1日2,000円で、まず座ってみる',
        ['co-ba ebisu のドロップインは、平日10時〜19時で1日2,000円です。会員でなくても、まず1日座って確かめられます。', '1階のコワーキングには Wi-Fi、電源、フォンブースがあります。月契約の前に、場所の空気を知る入口です。'],
        [('co-ba-ebisu', 3)]),
       ('midori-so-nakameguro', 'ポップインは1日3,300円、11日分で33,000円',
        ['MIDORI.so Nakameguro のポップインは、1日3,300円です。11日分のパッケージは33,000円で、週に2〜3日だけ来る人にも合います。', '本館のギャラリーは展示や撮影にも貸し出されます。働く場所の中に、会員以外の人が入る機会があります。'],
        [('midori-so-nakameguro', 8)]),
       ('lifork-otemachi', '30分単位で部屋を借りる、スタイルルーム',
        ['LIFORK 大手町のスタイルルームは B から L まで10室あり、4名用が30分1,650円、16名用の G が30分4,400円です。', '9:00〜21:00に、最低30分、以降15分単位で使えます。会員でなくても部屋単位で借りられる入口です。'],
        [('lifork-otemachi', 8)]),
       ('100banch', '平日17時から、約40分の見学ツアー',
        ['100BANCH には、平日の17時から約40分の施設見学ツアーがあります。料金は1人2,200円で、書籍が1冊つきます。', '会員でなくても中を見られる仕組みがあるので、コワーキングを探している人が雰囲気を確かめるのに向いています。'],
        [('100banch', 8)]),
      ],
      ctx=dict(term='ドロップイン', yomi='ドロップイン', title='ドロップインとは', body=['月契約をせずに、1日や数時間の単位でコワーキングを使うことです。施設によって「ポップイン」など別の名前で呼ばれます。', '料金は1日2,000〜3,300円ほどが目安です。会員になる前に、席の混み具合や音の大きさを自分で確かめられます。']),
      items=['co-ba-ebisu', 'midori-so-nakameguro', 'lifork-otemachi', '100banch']),

 dict(slug='24h', q='24時間使えるコワーキングはあるの？',
      a='あります。co-lab 渋谷キャスト、LIFORK 大手町、MIDORI.so Nakameguro、co-ba ebisu の1階は24時間365日使えます。深夜や休日の出入りは、スマートロックなど鍵を持ち歩かない仕組みで支えられています。',
      desc='24時間使えるコワーキングを、co-lab 渋谷キャスト・LIFORK 大手町・MIDORI.so・co-ba ebisu の公式情報から。',
      secs=[
       ('co-lab-shibuya-cast', '2003年から続く、24時間365日のシェアオフィス',
        ['co-lab 渋谷キャストは、24時間365日使えます。1〜2人のブースから12〜22人のルームまで、どの部屋も同じです。', '2階には窓際の共用スペースとキッチンがあります。夜も昼も、部屋の外に出て休める場所があります。'],
        [('co-lab-shibuya-cast', 1)]),
       ('lifork-otemachi', 'スマートロックで、受付のいない時間も出入りする',
        ['LIFORK 大手町のシェアオフィスは、24時間365日使えます（ビルの休館日を除く）。会員の入退室はスマートロックです。', '鍵を持ち歩かずに部屋に入れるので、深夜や休日の出入りも自分で完結します。'],
        [('lifork-otemachi', 4), ('lifork-otemachi', 2)]),
       ('midori-so-nakameguro', '古い建物でも、365日24時間',
        ['MIDORI.so Nakameguro は、365日24時間使えます。キッチン、ロッカー、無料のドリンクが備わります。', 'フリーデスクは月42,350円、固定デスクは月60,500円です。時間の制限がない分、契約は席の種類で選びます。'],
        [('midori-so-nakameguro', 2)]),
       ('co-ba-ebisu', '24時間のプランと、夜と週末だけのプラン',
        ['co-ba ebisu の1階は、毎日24時間使えるフリーアドレスが月30,000円です。', '平日の夜と週末だけの Night & Weekend が月12,000円、早朝の Early Bird が月6,500円と、使う時間帯で料金が変わります。'],
        [('co-ba-ebisu', 2)]),
      ],
      ctx=dict(term='スマートロック', yomi='スマートロック', title='スマートロックとは', body=['物理的な鍵ではなく、スマートフォンやカードで開ける電子の鍵です。LIFORK 大手町では会員の入退室に使われています。', '24時間使える施設では、受付のいない時間の出入りをどう管理するかが要になります。鍵を配らずに済む仕組みは、運営の手間を大きく減らします。']),
      items=['co-lab-shibuya-cast', 'lifork-otemachi', 'midori-so-nakameguro', 'co-ba-ebisu']),

 dict(slug='community-manager', q='「コミュニティマネージャー」は何をする人？',
      a='会員同士や会員と外の人をつなぎ、催しや相談の窓口になるスタッフです。席を管理する受付とは役目が違います。Business Airport では「伴走するパートナー」として置かれています。',
      desc='コミュニティマネージャーの役目を、Business Airport 青山・ARCH・SHIBUYA QWS の公式情報から。',
      secs=[
       ('business-airport-aoyama', '会員に伴走するコミュニティマネージャー',
        ['Business Airport 青山では、コミュニティマネージャーが会員に伴走します。受付の時間にはスタッフが常駐し、セキュリティも整っています。', 'どの拠点の会員も全拠点のコワーキングを使えます。人を紹介する役目の人がいるかどうかで、シェアオフィスの居心地は変わります。'],
        [('business-airport-aoyama', 2)]),
       ('toranomon-hills-arch', '助言と人のつなぎ役、チーフ・インキュベーション・オフィサー',
        ['ARCH では、2人のチーフ・インキュベーション・オフィサーが助言と人のつなぎ役を担います。名前は違いますが、役目はコミュニティマネージャーに近いものです。', 'メンタリング、ネットワーキング、トレーニングが施設のサービスの柱で、週ごとの交流会や車座の集まり、ピッチイベントも施設の中で開かれます。'],
        [('toranomon-hills-arch', 8)]),
       ('shibuya-qws', '専門家として支える QWS コモンズ',
        ['SHIBUYA QWS には、専門家として会員を支える QWS コモンズという会員区分があります。3人以上のチームで入るプロジェクトメンバーと同じフロアにいます。', '施設の中心の CROSS PARK は人が行き交う場所です。人をつなぐ役目を、スタッフだけでなく場所の形にも持たせています。'],
        [('shibuya-qws', 4)]),
      ],
      ctx=dict(term='コミュニティマネージャー', yomi='コミュニティマネージャー', title='コミュニティマネージャーとは', body=['コワーキングやシェアオフィスで、会員同士や会員と外の人をつなぐスタッフです。催しの企画や相談の窓口も担います。', '施設によって呼び名は違います。ARCH のチーフ・インキュベーション・オフィサーのように、助言と紹介を役目にする人を置く施設が増えています。']),
      items=['business-airport-aoyama', 'toranomon-hills-arch', 'shibuya-qws']),

 dict(slug='meeting-event', q='会議室やイベントスペースはどう使うの？',
      a='会議室は予約して時間単位で使い、イベントスペースはふだん共用の場所を催しのときだけ貸し切る形が多いです。WeWork 渋谷スクランブルスクエアには会議室が70室あり、部屋の大きさを選べます。',
      desc='会議室とイベントスペースの使い方を、WeWork 渋谷スクランブルスクエア・LIFORK 大手町・co-ba ebisu・SHIBUYA QWS の公式情報から。',
      secs=[
       ('wework-shibuya-scramble-square', '会議室70室と、催しの形に並べ替えるラウンジ',
        ['WeWork 渋谷スクランブルスクエアの会議室は70室です。少人数の打ち合わせから大きめの会議まで、部屋の大きさを選べます。', '42階のラウンジは催しの形に並べ替えられます。フォンブースもあり、オンラインの打ち合わせは席を離れて行えます。'],
        [('wework-shibuya-scramble-square', 4), ('wework-shibuya-scramble-square', 7)]),
       ('lifork-otemachi', '199.1㎡のレンタルラウンジを、60分44,000円で',
        ['LIFORK 大手町のレンタルラウンジは199.1㎡で、着席なら50名、立食なら60名まで入ります。130インチのスクリーンとワイヤレスマイクがあります。', '料金は60分44,000円で、最低60分、以降15分単位です。セミナー、交流会、表彰式、撮影、試写会に使われています。'],
        [('lifork-otemachi', 6), ('lifork-otemachi', 7)]),
       ('co-ba-ebisu', '70人の PARK と40人の CAFE、会員は半額',
        ['co-ba ebisu の1階には PARK と CAFE という2つの催しの場所があります。PARK は70人まで、CAFE は40人まで入り、会員は半額で借りられます。', 'ふだんは共用の場所として使い、催しのときだけ貸し切ります。作業と交流を同じフロアに置いています。'],
        [('co-ba-ebisu', 4), ('co-ba-ebisu', 5)]),
       ('shibuya-qws', '200名規模のホールと、全会員が使える会議室3室',
        ['SHIBUYA QWS の SCRAMBLE HALL は200名規模のイベントスペースです。渋谷のスクランブル交差点を見下ろす位置にあり、3面のスクリーン、音響、照明、控室を備えます。', '会議室は全会員が使える3室のほか、予約制の個室もあります。'],
        [('shibuya-qws', 6)]),
      ],
      ctx=dict(term='イベントスペース', yomi='イベントスペース', title='イベントスペースとは', body=['セミナーや交流会、発表会を開くための広い場所です。コワーキングでは、ラウンジや共用部を催しのときだけ貸し切る形がよく見られます。', '定員、スクリーンや音響の有無、会員の割引、時間単位の料金が比べる目安になります。']),
      items=['wework-shibuya-scramble-square', 'lifork-otemachi', 'co-ba-ebisu', 'shibuya-qws']),

 dict(slug='private-fixed', q='個室と固定席は、どんな人が選ぶの？',
      a='その場所を会社の拠点として置きたい人が選びます。法人登記、鍵のかかる部屋、荷物を置いたままにできる席が理由です。SAAI の4階の固定席は「法人登記も可能な専用デスク」で、月77,000円です。',
      desc='個室と固定席を選ぶ理由を、有楽町 SAAI・co-ba ebisu・ARCH・MIDORI.so の公式情報から。',
      secs=[
       ('saai-yurakucho', '法人登記のできる固定席と、4人までの個室',
        ['SAAI の4階の固定席は「法人登記も可能な専用デスク」で、月77,000円の固定ブースと、月33,000円のフリーデスクがあります。', '個室は「4人まで入居可能な家具付き専用個室」です。会社の住所をここに置きたい人の入口です。'],
        [('saai-yurakucho', 7)]),
       ('co-ba-ebisu', '2年の定期契約で借りる、8人から20人の部屋',
        ['co-ba ebisu の2階は個室オフィスのフロアです。シングル・ツインルームは約31〜34㎡で8人ほど、スイートルームは約48〜72㎡で10〜20人が入ります。', '2年の定期契約で、管理費を含みます。2階の入居者は月30,000円の追加プランで1階のコワーキングも使えます。'],
        [('co-ba-ebisu', 6), ('co-ba-ebisu', 7)]),
       ('toranomon-hills-arch', 'セキュリティのある第二のオフィスと、短期の部屋',
        ['ARCH の SMALL OFFICE は、セキュリティの確保されたセカンドオフィスです。複数の会社で進める新規事業にも向きます。', 'PROJECT ROOM は短期間のプロジェクト利用ができる小さなチーム向けの部屋です。集中して手を動かす期間だけ借りられます。'],
        [('toranomon-hills-arch', 4), ('toranomon-hills-arch', 5)]),
       ('midori-so-nakameguro', 'フリーデスク月42,350円と、固定デスク月60,500円',
        ['MIDORI.so Nakameguro の料金は、フリーデスクが月42,350円、固定デスクが月60,500円です。どちらも入会金は11,000円です。', '母屋には個室オフィスが入ります。本館の共用の場所と、母屋の閉じた部屋を、敷地の中で行き来します。'],
        [('midori-so-nakameguro', 4)]),
      ],
      ctx=dict(term='法人登記', yomi='ホウジントウキ', title='法人登記とは', body=['会社の所在地を公の記録に載せることです。コワーキングの中には、固定席や個室の契約で登記の住所に使える施設があります。', 'フリーデスクでは登記できない施設が多いので、会社の住所が必要な人は固定席か個室を選びます。']),
      items=['saai-yurakucho', 'co-ba-ebisu', 'toranomon-hills-arch', 'midori-so-nakameguro']),

 dict(slug='station', q='駅直結のコワーキングは、どこにあるの？',
      a='大手町駅直結の LIFORK 大手町と、渋谷駅直結の渋谷スクランブルスクエアに入る WeWork と SHIBUYA QWS があります。LIFORK 大手町は大手町駅の C8・C11・C12 出口から直結し、JR東京駅からも歩いて5分です。',
      desc='駅直結のコワーキングを、LIFORK 大手町・WeWork 渋谷スクランブルスクエア・SHIBUYA QWS・Business Airport 青山の公式情報から。',
      secs=[
       ('lifork-otemachi', '大手町駅の C8・C11・C12 出口から直結',
        ['LIFORK 大手町は、大手町ファーストスクエア ウエストタワーの1階と2階です。東京メトロ東西線・丸ノ内線・千代田線・半蔵門線、都営三田線の大手町駅から C8・C11・C12 出口で直結します。', 'JR東京駅丸の内北口からも歩いて5分です。集中して働く環境に重きを置いた拠点です。'],
        [('lifork-otemachi', 3)]),
       ('wework-shibuya-scramble-square', '渋谷駅直結、5路線が使える高層階',
        ['WeWork 渋谷スクランブルスクエアは、渋谷駅に直結する渋谷スクランブルスクエア東棟の37〜42階と45階です。', 'JR山手線、東急東横線・田園都市線、東京メトロ半蔵門線・副都心線、京王井の頭線が乗り入れます。'],
        [('wework-shibuya-scramble-square', 8), ('wework-shibuya-scramble-square', 1)]),
       ('shibuya-qws', '同じ渋谷スクランブルスクエアの15階',
        ['SHIBUYA QWS は、渋谷スクランブルスクエア東棟の15階にあります。約2,600㎡のフロアに、PROJECT BASE や200名規模の SCRAMBLE HALL が入ります。', '営業時間は9:00〜22:00（最終入館21:30）です。駅の上の建物に、WeWork と QWS の2つのコワーキングがあります。'],
        [('shibuya-qws', 3)]),
       ('business-airport-aoyama', '直結ではなくても、外苑前駅から3分',
        ['Business Airport 青山は、東京メトロ銀座線の外苑前駅1a出口から歩いて3分です。スプライン青山東急ビルの4階と6階に入ります。', 'コワーキングは平日7:00〜22:00に使えます。出社前の1時間を青山で過ごす使い方ができます。'],
        [('business-airport-aoyama', 5)]),
      ],
      ctx=dict(term='駅直結', yomi='エキチョクケツ', title='駅直結とは', body=['駅の改札や地下通路から、外に出ずに建物へ入れることです。雨の日や荷物の多い日に差が出ます。', '直結でなくても、駅から3〜5分の施設は多くあります。通う頻度と、駅からの道の様子をあわせて選ぶのが目安です。']),
      items=['lifork-otemachi', 'wework-shibuya-scramble-square', 'shibuya-qws', 'business-airport-aoyama']),

 dict(slug='reuse', q='古い建物を使ったコワーキングはあるの？',
      a='あります。MIDORI.so Nakameguro は、蔦に覆われた廃屋を改装した2棟のシェアオフィスです。古い建物の骨格を残したまま直しているので、新しいビルにはない凹凸と陰影があります。',
      desc='古い建物を直したコワーキングを、MIDORI.so Nakameguro を中心に、co-ba ebisu・co-lab 渋谷キャストとの対比で。',
      secs=[
       ('midori-so-nakameguro', '蔦に覆われた廃屋を、本館と母屋の2棟に',
        ['MIDORI.so Nakameguro は、蔦に覆われた廃屋を改装して生まれました。本館の3階にワークスペース、ラウンジ、会議室、ギャラリーがあり、母屋には個室オフィスが入ります。', '古い建物の骨格を残したまま直しているので、新しいビルにはない凹凸と陰影があります。365日24時間使えます。'],
        [('midori-so-nakameguro', 1), ('midori-so-nakameguro', 3)]),
       ('co-ba-ebisu', '対照に、2019年11月に開いた新しい建物',
        ['co-ba ebisu は、JP noie 恵比寿西の1階と2階に2019年11月に開きました。1,573.42㎡の2フロアで、天井の高い共用部があります。', 'デザインのテーマは「WORK ASSEMBLE」。新しい建物では、内装のテーマで場所の性格を作ります。'],
        [('co-ba-ebisu', 1)]),
       ('co-lab-shibuya-cast', '17階建ての低層階に入る例',
        ['co-lab 渋谷キャストは、「不揃いの調和」を設計の考え方に掲げる17階建ての渋谷キャストの1階と2階に入ります。', '隣にはカフェ「Are」があり、建物の外と中がゆるくつながっています。古い建物か新しい建物かより、街との接し方が場所の印象を決めます。'],
        [('co-lab-shibuya-cast', 8)]),
      ],
      ctx=dict(term='改装', yomi='カイソウ', title='改装とは', body=['古い建物の骨格を残したまま、内装や設備を直して使うことです。MIDORI.so Nakameguro は蔦に覆われた廃屋をこの方法で直しました。', '新築では出せない表情が残るので、古い建物を持っている人にとって、コワーキングは有力な使い道の一つです。']),
      items=['midori-so-nakameguro', 'co-ba-ebisu', 'co-lab-shibuya-cast']),
]


# ==== 2026-09-27 Q&A を10本追加（110施設になったため）。答えと本文は各施設の記事データの事実だけ ====
QUESTIONS += [{'slug': 'solo-room', 'q': 'ひとりで集中できる個室のあるコワーキングは？', 'a': '定員1名の個室を並べた施設があります。H¹T池袋東口 THE GARDEN と H¹T新宿西口は1名用のルームが18室、SENQ 目黒はソロブースが26室です。', 'desc': 'ひとりで集中できる個室のあるコワーキングを、H¹T・ワークスタイリング品川・SENQ 目黒の公式情報から。', 'secs': [('h1t-ikebukuro-higashiguchi-the-garden', '定員1名のルームが18室', ['H¹T池袋東口 THE GARDEN は、池袋伊藤ビルの10階にあります。定員1名のルームが18室と、4名・6名の会議室があります。', '平日も土日祝も、7時から22時30分まで開いています。'], [('h1t-ikebukuro-higashiguchi-the-garden', 1)]), ('h1t-shinjuku-nishiguchi', '個室18室とボックス、会議室7室', ['H¹T新宿西口は、1名用のルーム18室、ボックス、会議室7室がそろう9階です。オープンスペースは17名です。', '営業は全日7時から22時までです。'], [('h1t-shinjuku-nishiguchi', 1)]), ('workstyling-shinagawa', '「極上のソロワークができる、働くための巣」', ['ワークスタイリング品川のコンセプトは「極上のソロワークができる、働くための巣」です。', 'NBF品川タワーの5階と6階にあり、JR品川駅からペデストリアンデッキでつながっています。'], [('workstyling-shinagawa', 1)]), ('senq-meguro', 'ソロブース26室と、自宅のようなラウンジ', ['SENQ 目黒は、ソロブース26室とルーム13室を持つ8階の施設です。コンセプトは「暮らしながら働く」です。', 'コワーキングは平日9時から22時まで、ルームは24時間使えます。'], [('senq-meguro', 1)])], 'ctx': None, 'items': ['h1t-ikebukuro-higashiguchi-the-garden', 'h1t-shinjuku-nishiguchi', 'workstyling-shinagawa', 'senq-meguro']}, {'slug': 'weekend', 'q': '土日も使えるコワーキングは？', 'a': '土日も平日と同じ時間に開く施設があります。ワークスタイリング八重洲南口とワークスタイリング銀座は土日も8時から22時まで、MIDORI.so Kichijoji は毎日8時から23時までです。', 'desc': '土日も使えるコワーキングを、ワークスタイリング・H¹T・MIDORI.so Kichijoji の公式情報から。', 'secs': [('workstyling-yaesu-minamiguchi', '土日も朝8時から夜22時まで', ['ワークスタイリング八重洲南口は、パシフィックセンチュリープレイス丸の内の2階にあります。', '平日も土日も8時から22時まで開いています。東京駅から歩いて3分です。'], [('workstyling-yaesu-minamiguchi', 1)]), ('workstyling-ginza', '銀座駅から1分、土日祝も22時まで', ['ワークスタイリング銀座は、ギンザ・グラッセの9階にあります。', '平日も土日祝も8時から22時まで。東京メトロ銀座駅から歩いて1分です。'], [('workstyling-ginza', 1)]), ('h1t-shinjuku-nishiguchi', '全日7時から22時まで', ['H¹T新宿西口は、全日7時から22時まで開いています。', '新宿駅西口から歩いて2分の西新宿昭和ビル9階です。'], [('h1t-shinjuku-nishiguchi', 1)]), ('midori-so-kichijoji', '吉祥寺PARCOの8階、毎日23時まで', ['MIDORI.so Kichijoji は、吉祥寺PARCOの8階にあるコワーキングです。', '営業は毎日8時から23時まで。ワークスペース、会議室、キッチン、ラウンジ、ブースがそろいます。'], [('midori-so-kichijoji', 4)])], 'ctx': None, 'items': ['workstyling-yaesu-minamiguchi', 'workstyling-ginza', 'h1t-shinjuku-nishiguchi', 'midori-so-kichijoji']}, {'slug': 'early-morning', 'q': '朝早くから使えるコワーキングは？', 'a': '朝7時から使える施設が多くあります。Business Airport の多くの拠点はコワーキングが平日7時から、H¹T池袋東口 THE GARDEN は毎日7時から、.andwork 渋谷のドロップインは7時から24時までです。', 'desc': '朝早くから使えるコワーキングを、Business Airport・H¹T・.andwork・BASE POINT の公式情報から。', 'secs': [('business-airport-kudanshita', '九段会館テラス、平日7時から', ['Business Airport 九段下は、九段会館テラスの1階にあります。お濠の緑と水景に面しています。', 'コワーキングは平日7時から22時まで。サービスオフィスは24時間使えます。'], [('business-airport-kudanshita', 1)]), ('h1t-ikebukuro-higashiguchi-the-garden', '毎日7時から22時30分まで', ['H¹T池袋東口 THE GARDEN は、平日も土日祝も7時から22時30分まで開いています。', 'JR池袋駅の北改札から歩いて3分です。'], [('h1t-ikebukuro-higashiguchi-the-garden', 1)]), ('andwork-shibuya', 'ドロップインは7時から24時まで', ['.andwork 渋谷は、The Millennials 渋谷のロビーを仕事場にした施設です。', 'ドロップインは7時から24時まで、週・月の会員は24時間使えます。1時間1,100円、1日3,300円です。'], [('andwork-shibuya', 1)]), ('base-point-shinjuku', '1階のワーキングカフェが7時から', ['BASE POINT は、1階がワーキングカフェ、2階が会議室、3階がシェアオフィスです。', '営業は全日7時から23時まで。7時から10時と20時から23時は無人の時間です。'], [('base-point-shinjuku', 3)])], 'ctx': None, 'items': ['business-airport-kudanshita', 'h1t-ikebukuro-higashiguchi-the-garden', 'andwork-shibuya', 'base-point-shinjuku']}, {'slug': 'hotel', 'q': 'ホテルの中のコワーキングは、どう使うの？', 'a': 'ロビーやラウンジを、時間や日にち単位で借りて使います。.andwork 渋谷は1時間1,100円から、.andwork 麻布十番は1時間800円からです。MIDORI.so Nihonbashi は、昼は働く場所、夜は泊まる場所として使えます。', 'desc': 'ホテルの中のコワーキングの使い方を、.andwork・MIDORI.so Nihonbashi の公式情報から。', 'secs': [('andwork-shibuya', 'ホテルのロビーが、世界中のワーカーの仕事場に', ['.andwork 渋谷は、The Millennials 渋谷の中にあります。コワーキングエリア、ラウンジ、キッチン、フォーン・ブースがそろいます。', '料金は1時間1,100円、1日3,300円、月29,000円から34,000円です。'], [('andwork-shibuya', 1)]), ('andwork-azabujuban', '2階のラウンジと、最上階のバー', ['.andwork 麻布十番は、THE LIVELY 東京麻布十番の中にあります。2階がラウンジ、最上階がバーです。', '営業は8時から22時まで。1時間800円、1日2,500円、月34,000円です。'], [('andwork-azabujuban', 1)]), ('andwork-shibuya-higashi', 'ホテル1階の、カフェ兼コワーキング', ['.andwork 渋谷東は、HOTEL GRAPHY 渋谷の1階にあるカフェ兼コワーキングスペースです。', '営業は月・火・木・金曜日の11時から18時まで。料金は1日2,000円です。'], [('andwork-shibuya-higashi', 2)]), ('midori-so-nihonbashi', '働くことと泊まることが同じ建物に', ['MIDORI.so Nihonbashi は、1階がカフェ・バー・ギャラリー、2階がラウンジ、3階と4階が仕事と眠りの部屋です。', 'ポップインは昼が1日2,200円、夜が1泊8,800円で、入会金と会費はありません。'], [('midori-so-nihonbashi', 1)])], 'ctx': None, 'items': ['andwork-shibuya', 'andwork-azabujuban', 'andwork-shibuya-higashi', 'midori-so-nihonbashi']}, {'slug': 'price', 'q': 'コワーキングの月額料金は、どのくらい？', 'a': '共用の席を使うプランは、月1万円台から6万円台まで幅があります。SAAI のフリーデスクは月33,000円、MIDORI.so のフリーデスクは月42,350円からです。', 'desc': 'コワーキングの月額料金を、有楽町 SAAI・MIDORI.so・DIAGONAL RUN TOKYO・.andwork・THE HUB の公式情報から。', 'secs': [('saai-yurakucho', 'コミュニティ 月16,500円から', ['有楽町 SAAI は、コミュニティ会員が月16,500円、フリーデスクが月33,000円、固定ブースが月77,000円です。', '新東京ビルの地下1階、1階、4階を使う事業創造のコミュニティです。'], [('saai-yurakucho', 1)]), ('midori-so-nakameguro', 'フリーデスク 月42,350円、固定デスク 月60,500円', ['MIDORI.so Nakameguro は、フリーデスクが月42,350円、固定デスクが月60,500円です。入会金は11,000円です。', '蔦に覆われた廃屋を改装した、本館と母屋の2棟のシェアオフィスです。'], [('midori-so-nakameguro', 1)]), ('diagonal-run-tokyo', 'フリーデスク 月18,700円から', ['DIAGONAL RUN TOKYO は、フリーデスクが月18,700円からです。ドロップインは1日3,300円、平日は1時間660円でも使えます。', '京橋MIDビルの4階にあり、宝町駅から歩いて約1分です。'], [('diagonal-run-tokyo', 1)]), ('the-hub-nihonbashi-odenmacho', '1拠点プラン 月8,800円', ['THE HUB 日本橋大伝馬町は、1拠点プランが月8,800円です。個室のレンタルオフィスは月45,100円からです。', '有人フロントのある、全81室の個室オフィスです。'], [('the-hub-nihonbashi-odenmacho', 1)])], 'ctx': None, 'items': ['saai-yurakucho', 'midori-so-nakameguro', 'diagonal-run-tokyo', 'the-hub-nihonbashi-odenmacho']}, {'slug': 'hourly', 'q': '1時間から使えるコワーキングは？', 'a': '1時間単位のドロップインを用意している施設があります。DIAGONAL RUN TOKYO は平日1時間660円、.andwork 麻布十番は1時間800円、.andwork 渋谷は1時間1,100円です。', 'desc': '1時間から使えるコワーキングを、DIAGONAL RUN TOKYO・.andwork・MIDORI.so Nihonbashi の公式情報から。', 'secs': [('diagonal-run-tokyo', '平日は1時間660円', ['DIAGONAL RUN TOKYO は、平日なら1時間660円で使えます。1日は3,300円です。', '東京と全国各地の人と企業とアイデアが、斜めに交わる場所を掲げています。'], [('diagonal-run-tokyo', 1)]), ('andwork-azabujuban', '1時間800円、10回券もある', ['.andwork 麻布十番は、1時間800円、1日2,500円です。10回券は17,500円です。', '営業は8時から22時までです。'], [('andwork-azabujuban', 1)]), ('andwork-shibuya', '1時間1,100円、ドロップインは24時まで', ['.andwork 渋谷は、1時間1,100円、1日3,300円です。', 'ドロップインは7時から24時まで使えます。'], [('andwork-shibuya', 1)]), ('midori-so-nihonbashi', '昼のポップイン 1日2,200円', ['MIDORI.so Nihonbashi は、昼のポップインが1日2,200円です。入会金と会費はありません。', '夜は1泊8,800円で、同じ建物に泊まれます。'], [('midori-so-nihonbashi', 1)])], 'ctx': None, 'items': ['diagonal-run-tokyo', 'andwork-azabujuban', 'andwork-shibuya', 'midori-so-nihonbashi']}, {'slug': 'rooftop', 'q': '屋上やテラスのあるコワーキングは？', 'a': '屋上に庭や畑を持つ施設や、高層階にテラスを持つ施設があります。SENQ 六本木は9階にスカイテラス、MIDORI.so Bakuroyokoyama は屋上に畑、THE HUB 日本橋兜町は屋上テラスがあります。', 'desc': '屋上やテラスのあるコワーキングを、SENQ 六本木・MIDORI.so・THE HUB の公式情報から。', 'secs': [('senq-roppongi', '新六本木ビル9階のスカイテラス', ['SENQ 六本木の9階には、約70席のコワーキング、会議室、カフェコーナーとスカイテラスがあります。', 'テーマは CHANGE THE THEORY です。個室は24時間365日使えます。'], [('senq-roppongi', 1)]), ('midori-so-bakuroyokoyama', '昭和のビルの屋上に畑', ['MIDORI.so Bakuroyokoyama は、昭和のビル7階分にカフェ、印刷の工房、ギャラリー、ワークスペースを入れた施設です。', '屋上には庭があり、畑になっています。'], [('midori-so-bakuroyokoyama', 1)]), ('the-hub-nihonbashi-kabutocho', '全室完全個室と屋上テラス', ['THE HUB 日本橋兜町は、SOHO物件を大胆にリニューアルしたオフィスです。全室が完全個室で、屋上テラスがあります。', '会議室は4名用が3室。個室のレンタルオフィスは月75,350円からです。'], [('the-hub-nihonbashi-kabutocho', 1)]), ('the-hub-ginza-oct', '一棟まるごとのシェアオフィスと屋上テラス', ['THE HUB 銀座OCT は、一棟まるごとのシェアオフィスです。4〜35名用の個室と、屋上テラスがあります。', 'ラウンジと会議室は7時から22時まで、予約制で使えます。'], [('the-hub-ginza-oct', 1)])], 'ctx': None, 'items': ['senq-roppongi', 'midori-so-bakuroyokoyama', 'the-hub-nihonbashi-kabutocho', 'the-hub-ginza-oct']}, {'slug': 'design-theme', 'q': '内装にテーマのあるコワーキングは？', 'a': '街の歴史や物語を内装に取り入れた施設があります。ワークスタイリングは日比谷が「ZEN MODERN」、新宿三井ビルディングが「RETRO FUTURE」、Business Airport は日比谷が劇場、新橋が鉄道をモチーフにしています。', 'desc': '内装にテーマのあるコワーキングを、ワークスタイリング・Business Airport の公式情報から。', 'secs': [('workstyling-tokyo-midtown-hibiya', '日本の伝統文様の「ZEN MODERN」', ['ワークスタイリング 東京ミッドタウン日比谷は、日比谷三井タワーの12階にあります。', '日本の伝統文様をあしらった「ZEN MODERN」がデザインのテーマです。'], [('workstyling-tokyo-midtown-hibiya', 1)]), ('workstyling-shinjuku-mitsui-building', '過去と未来を横断する「RETRO FUTURE」', ['ワークスタイリング 新宿三井ビルディングは、11階にあります。デザインのテーマは「RETRO FUTURE」です。', 'FLEX の会員は24時間入退室できます。'], [('workstyling-shinjuku-mitsui-building', 1)]), ('business-airport-hibiya', '劇場をモチーフに、緑と芸術に囲まれて', ['Business Airport 日比谷は、東宝日比谷ビルの9階にあります。劇場をモチーフにしたワークプレイスです。', 'コワーキングは平日7時から22時まで、土日祝は10時から18時までです。'], [('business-airport-hibiya', 1)]), ('business-airport-shimbashi', '鉄道発祥の地を思わせるモチーフ', ['Business Airport 新橋は、新橋プレイスの6階から8階にあります。鉄道発祥の地を思わせるモチーフが満載です。', '会議室は4室あります。'], [('business-airport-shimbashi', 1)])], 'ctx': None, 'items': ['workstyling-tokyo-midtown-hibiya', 'workstyling-shinjuku-mitsui-building', 'business-airport-hibiya', 'business-airport-shimbashi']}, {'slug': 'high-floor', 'q': '眺めのいい高層階のコワーキングは？', 'a': '超高層ビルの上の階を使う施設があります。WeWork 渋谷スクランブルスクエアは37〜42階と45階、Hills House 麻布台は東京タワーを望む33・34階、ワークスタイリング 霞が関ビルディングは36階です。', 'desc': '眺めのいい高層階のコワーキングを、WeWork・Hills House・ワークスタイリング・Business Airport の公式情報から。', 'secs': [('wework-shibuya-scramble-square', '渋谷駅直結の37〜42階と45階', ['WeWork 渋谷スクランブルスクエアは、地上47階のビルの37〜42階と45階を使います。', '会議室は70室。天井の高さは3,000〜3,200mm です。'], [('wework-shibuya-scramble-square', 2)]), ('hills-house-azabudai', '東京タワーを望む33・34階', ['Hills House 麻布台は、麻布台ヒルズ森JPタワーの33階と34階にある会員制のエリアです。', '飲食スペースは333席、ワークスペースは49席です。'], [('hills-house-azabudai', 1)]), ('workstyling-kasumigaseki-building', '霞が関ビルディングの36階', ['ワークスタイリング 霞が関ビルディングは、36階にあります。', '銀座線の虎ノ門駅から歩いて2分です。'], [('workstyling-kasumigaseki-building', 1)]), ('business-airport-shinagawa', '太陽生命品川ビルの28階', ['Business Airport 品川は、太陽生命品川ビルの28階にあります。', '1〜6名のルーム、デスク、コワーキング、会議室3室がそろいます。'], [('business-airport-shinagawa', 1)])], 'ctx': None, 'items': ['wework-shibuya-scramble-square', 'hills-house-azabudai', 'workstyling-kasumigaseki-building', 'business-airport-shinagawa']}, {'slug': 'seminar', 'q': 'セミナーや大人数の会議ができるコワーキングは？', 'a': '大きな会議室やイベントスペースを持つ施設があります。Global Business Hub Tokyo は最大200名のイベントスペース、ワークスタイリング恵比寿は150名までのカンファレンスルーム、X-NIHONBASHI TOWER はシアター形式で約120席です。', 'desc': '大人数で使えるコワーキングを、Global Business Hub Tokyo・ワークスタイリング恵比寿・X-NIHONBASHI TOWER・CROSSCOOP の公式情報から。', 'secs': [('global-business-hub-tokyo', '最大200名のイベントスペース', ['Global Business Hub Tokyo は、大手町フィナンシャルシティ グランキューブの3階にあります。', '家具付きオフィス50区画、会議室14室、最大200名のイベントスペースがそろいます。'], [('global-business-hub-tokyo', 1)]), ('workstyling-ebisu', '13〜150名のカンファレンスルーム', ['ワークスタイリング恵比寿には、13名から150名まで使えるカンファレンスルームがあります。', '東京メトロ恵比寿駅から歩いて1分のフジワラビルディング8階です。'], [('workstyling-ebisu', 1)]), ('x-nihonbashi-tower', 'シアター形式で約120席', ['X-NIHONBASHI TOWER は、日本橋三井タワーの7階にある宇宙ビジネスの共創拠点です。', '307㎡で、シアター形式なら約120席、立食なら約150名が入れます。'], [('x-nihonbashi-tower', 1)]), ('crosscoop-shimbashi', '72名のセミナールーム', ['CROSSCOOP 新橋には、72名のセミナールームと、約96席のラウンジがあります。', '個室は10名から100名用まで。共有施設は24時間使えます。'], [('crosscoop-shimbashi', 1)])], 'ctx': None, 'items': ['global-business-hub-tokyo', 'workstyling-ebisu', 'x-nihonbashi-tower', 'crosscoop-shimbashi']}]
